disabled_rules:
- implicit_getter

opt_in_rules:
- empty_count
- empty_string
- file_name_no_space
- generic_type_name
- implicit_return
- multiline_parameters
- no_space_in_method_call
- redundant_void_return
- vertical_whitespace_closing_braces
- trailing_whitespace

file_length:
    warning: 500
    error: 600
    ignore_comment_only_lines: false

function_body_length:
  warning: 100
  error: 140

line_length:
    warning: 180
    error: 200
    ignores_function_declarations: false
    ignores_comments: true
    ignores_urls: true

identifier_name:
max_length:
    warning: 45
    error: 60
min_length:
    warning: 1
